[package]
name = "cmd-args"
version = "0.1.0"
authors = ["Benjamin Eder"]
edition = "2018"
license = "MIT"
description = "Command line argument parser with nested command support"
readme = "README.md"
repository = "https://github.com/bennyboer/cmd-args"

[dependencies]
